routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();
Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
Route::resource('user', 'UserController')->except(['show', 'create']);
Route::resource('course', 'CourseController')->except(['show', 'create']);
Route::resource('subscription', 'SubscriptionsController')->except(['show', 'create']);


Route::get('getuser/{cpf}', 'GetController@getUser')->name('get.user'); 
Route::get('getcourses/{id?}', 'GetController@getCourses')->name('get.courses'); 

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>SWCOURSES</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!--- fontawasome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">

</head>
<body>
    <div id="app">
        @auth
            <nav class="navbar navbar-expand-md navbar-light bg-primary shadow-sm">
                <div class="container-fluid m-0 p-0">
                    <a class="navbar-brand m-0 p-0" href="{{ url('/') }}">
                        <h3 class="m-0 p-0 text-white"><b>SW</b>Course</h3>
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- Left Side Of Navbar -->
                        <ul class="navbar-nav mr-auto ml-5 ">
                            <li class="nav-item mr-4">
                                <a class="nav-link text-white" href="{{ route('user.index') }}"><i class="fas fa-users"></i> Usuários </a>
                            </li>
                            <li class="nav-item mr-4">
                                <a class="nav-link text-white" href="{{ route('course.index') }}"><i class="fas fa-book"></i> Cursos </a>
                            </li>
                            <li class="nav-item mr-4">
                                <a class="nav-link text-white" href="{{ route('subscription.index') }}"><i class="fas fa-address-book"></i> Inscrições </a>
                            </li>
                        </ul>

                        <!-- Right Side Of Navbar -->
                        <ul class="navbar-nav ml-auto">
                            <!-- Authentication Links -->
                            @guest
                                @if (Route::has('register'))
                                    <li class="nav-item">
                                        <b><a class="nav-link text-white" href="{{ route('register') }}">{{ __('Cadastrar-se') }}</a></b>
                                    </li>
                                @endif
                            @else
                                <li class="nav-item dropdown">
                                    <a id="navbarDropdown" class="nav-link text-white dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                        {{ Auth::user()->name }}
                                    </a>

                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                        document.getElementById('logout-form').submit();">
                                            {{ __('Logout') }}
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                            @csrf
                                        </form>
                                    </div>
                                </li>
                            @endguest
                        </ul>
                    </div>
                </div>
            </nav>
        @endauth

        
        @yield('content')

    </div>


</body>
</html>